"""scraper: provenance, scrape_runs, no-vitales nullable

Revision ID: 02add458a3a3
Revises: 4ea694e9d6b2
Create Date: 2026-06-17 12:47:32.346865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02add458a3a3'
down_revision = 'a7f3c9e1b204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    with op.batch_alter_table('inverters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=False, server_default=sa.text("'manual'")))
        batch_op.add_column(sa.Column('source_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('scraped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.alter_column('y',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('power_max',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('I_max_input',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('I_max_output',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_inverters_external_id'), ['external_id'], unique=False)

    with op.batch_alter_table('panels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=False, server_default=sa.text("'manual'")))
        batch_op.add_column(sa.Column('source_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('scraped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.alter_column('y',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('tcp',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('tcv',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('isc',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('t_noct',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('width',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_panels_external_id'), ['external_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panels_external_id'))
        batch_op.alter_column('width',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('t_noct',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('isc',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('tcv',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('tcp',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('y',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('is_locked')
        batch_op.drop_column('scraped_at')
        batch_op.drop_column('external_id')
        batch_op.drop_column('source_url')
        batch_op.drop_column('source')

    with op.batch_alter_table('inverters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inverters_external_id'))
        batch_op.alter_column('I_max_output',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('I_max_input',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('power_max',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('y',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('is_locked')
        batch_op.drop_column('scraped_at')
        batch_op.drop_column('external_id')
        batch_op.drop_column('source_url')
        batch_op.drop_column('source')

    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
