"""rol de plataforma (is_platform_admin)

Revision ID: 2354f52b1d15
Revises: 4ea694e9d6b2
Create Date: 2026-06-17 09:14:22.157755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2354f52b1d15'
down_revision = '4ea694e9d6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_platform_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_platform_admin')
    # ### end Alembic commands ###
