"""esquema inicial completo (auth, org, proyectos, catalogos/marketplace)

Revision ID: 5b14b2966d4e
Revises: 
Create Date: 2026-06-15 17:08:29.756780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b14b2966d4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation_defaults',
    sa.Column('dc_material', sa.String(length=100), nullable=False),
    sa.Column('dc_modelo', sa.String(length=100), nullable=False),
    sa.Column('ac_material', sa.String(length=100), nullable=False),
    sa.Column('ac_modelo', sa.String(length=100), nullable=False),
    sa.Column('tierra_material', sa.String(length=100), nullable=False),
    sa.Column('tierra_modelo', sa.String(length=100), nullable=False),
    sa.Column('dc_sobretensiones_modelo', sa.String(length=100), nullable=False),
    sa.Column('dc_fusibles_modelo', sa.String(length=100), nullable=False),
    sa.Column('dc_portafusibles', sa.String(length=100), nullable=False),
    sa.Column('dc_magnetotermico_modelo', sa.String(length=100), nullable=False),
    sa.Column('ac_diferencial_modelo', sa.String(length=100), nullable=False),
    sa.Column('ac_magnetotermico_modelo', sa.String(length=100), nullable=False),
    sa.Column('inyeccion_cero_modelo', sa.String(length=100), nullable=False),
    sa.Column('dispositivo_medida_modelo', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_installation_defaults'))
    )
    op.create_table('organizations',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('catalogs',
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_catalogs_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalogs'))
    )
    op.create_index(op.f('ix_catalogs_org_id'), 'catalogs', ['org_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_memberships_org_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_member_user_org')
    )
    op.create_table('catalog_subscriptions',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], name=op.f('fk_catalog_subscriptions_catalog_id_catalogs')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_catalog_subscriptions_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_subscriptions')),
    sa.UniqueConstraint('org_id', 'catalog_id', name='uq_sub_org_catalog')
    )
    op.create_index(op.f('ix_catalog_subscriptions_catalog_id'), 'catalog_subscriptions', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_catalog_subscriptions_org_id'), 'catalog_subscriptions', ['org_id'], unique=False)
    op.create_table('inverters',
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('power_max', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('vmax', sa.Float(), nullable=False),
    sa.Column('I_max_input', sa.Float(), nullable=False),
    sa.Column('I_max_output', sa.Float(), nullable=False),
    sa.Column('datasheet', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], name=op.f('fk_inverters_catalog_id_catalogs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inverters')),
    sa.UniqueConstraint('nombre', name=op.f('uq_inverters_nombre'))
    )
    op.create_index(op.f('ix_inverters_catalog_id'), 'inverters', ['catalog_id'], unique=False)
    op.create_table('panels',
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('tcp', sa.Float(), nullable=False),
    sa.Column('tcv', sa.Float(), nullable=False),
    sa.Column('voc', sa.Float(), nullable=False),
    sa.Column('vmp', sa.Float(), nullable=False),
    sa.Column('imp', sa.Float(), nullable=False),
    sa.Column('isc', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('t_noct', sa.Float(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('datasheet', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], name=op.f('fk_panels_catalog_id_catalogs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_panels')),
    sa.UniqueConstraint('nombre', name=op.f('uq_panels_nombre'))
    )
    op.create_index(op.f('ix_panels_catalog_id'), 'panels', ['catalog_id'], unique=False)
    op.create_table('wires',
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('seccion', sa.Float(), nullable=False),
    sa.Column('corriente', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('material', sa.String(length=10), nullable=False),
    sa.Column('no_conductores', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], name=op.f('fk_wires_catalog_id_catalogs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wires'))
    )
    op.create_index(op.f('ix_wires_catalog_id'), 'wires', ['catalog_id'], unique=False)
    op.create_table('projects',
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('necesidad', sa.Float(), nullable=True),
    sa.Column('autoconsumo', sa.Float(), nullable=True),
    sa.Column('coplanar', sa.Boolean(), nullable=True),
    sa.Column('inclinacion', sa.Float(), nullable=True),
    sa.Column('azimut', sa.Float(), nullable=True),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('inverter_id', sa.Integer(), nullable=True),
    sa.Column('referencia_catastral', sa.String(length=40), nullable=True),
    sa.Column('cups', sa.String(length=40), nullable=True),
    sa.Column('compania', sa.String(length=80), nullable=True),
    sa.Column('potencia_contratada', sa.Float(), nullable=True),
    sa.Column('tipo_voltaje', sa.String(length=20), nullable=True),
    sa.Column('resultados', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inverter_id'], ['inverters.id'], name=op.f('fk_projects_inverter_id_inverters')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_projects_org_id_organizations')),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], name=op.f('fk_projects_panel_id_panels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_wires_catalog_id'), table_name='wires')
    op.drop_table('wires')
    op.drop_index(op.f('ix_panels_catalog_id'), table_name='panels')
    op.drop_table('panels')
    op.drop_index(op.f('ix_inverters_catalog_id'), table_name='inverters')
    op.drop_table('inverters')
    op.drop_index(op.f('ix_catalog_subscriptions_org_id'), table_name='catalog_subscriptions')
    op.drop_index(op.f('ix_catalog_subscriptions_catalog_id'), table_name='catalog_subscriptions')
    op.drop_table('catalog_subscriptions')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_catalogs_org_id'), table_name='catalogs')
    op.drop_table('catalogs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('installation_defaults')
    # ### end Alembic commands ###
